[local]
127.0.0.1	ansible_connection=local

[usb]
192.168.55.1	ansible_user=ubuntu ansible_password=ubuntu ansible_sudo_pass=ubuntu

[pocket-infer-3351]
10.0.0.217	ansible_user=ubuntu ansible_password=ubuntu ansible_sudo_pass=ubuntu

[pocket-infer-4fb2]
10.0.0.50	ansible_user=ubuntu ansible_password=ubuntu ansible_sudo_pass=ubuntu

[pocket-infer-317d]
pocket-infer-317d	ansible_user=ubuntu ansible_password=ubuntu ansible_sudo_pass=ubuntu
