---
- name: Install ollama
  shell: curl -fsSL https://ollama.com/install.sh | sh
  args:
    creates: /usr/local/bin/ollama
  become: true

- name: Collect ollama models
  command: python -c "import re;from subprocess import run;foo=run(['ollama', 'ls'], capture_output=True).stdout.decode('utf-8').split('\n')[1:-1];bar=[re.match(r'(\S+)\s+(\S+).*', x).groups() for x in foo];print('\n'.join([':'.join(x) for x in bar]))"
  register: models

- name: Install Ministral ollama model
  command: ollama pull ministral-3:3B
  when: "'ministral-3:3B:f04aa1c738f6' not in models.stdout_lines"

- name: Install Qwen ollama model
  command: ollama pull qwen3-vl:2b
  when: "'qwen3-vl:2b:0635d9d857d4' not in models.stdout_lines"
